version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - backend_net

  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    networks:
        - backend_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: test1234
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001" 
    depends_on:
      - postgres
         
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - backend_net

  todoitemdetails.api:
    image: ${DOCKER_REGISTRY-}todoitemdetailsapi
    container_name: TodoItemDetails
    build:
      context: .
      dockerfile: TodoItemDetails.API/Dockerfile
    networks:
        - backend_net

  todolist.api:
    image: ${DOCKER_REGISTRY-}todolistapi
    container_name: TodoList
    build:
      context: .
      dockerfile: TodoList.API/Dockerfile
    networks:
        - backend_net

volumes:
  postgres-data:
  mongodb-data:

networks:
  backend_net:
    driver: bridge

